### ISSUE TITLE
JSON <-> BT++ convertion

### ISSUE THREAD

**Issue by facontidavide** [miccol/Behavior-Tree#10]
Hi Michele,

I noticed you mentioned :

"I am in contact with the developer of Behavior3.com I also had in mind of doing a parsing from JSON files"

I am thinking to do the same, and I would like (if you want) to collaborate this time and avoid replicated work.
Few preliminary thoughts:

1) To generate a JSON from a BT++ is pretty easy.
2) To generate a BT++ from a JSON file is, on the other hand, slightly more complicated, because it requires a proper factory and any user defined action / condition will need to register an allocating method to this factory.

I have a design in mind, but I wonder if you already have some idea or not about it.

**Comment by miccol** [comment]
What I have done so far is available here http://michelecolledanchise.com/editor/#/dash/home <http://michelecolledanchise.com/editor/#/dash/home>

but I prefer coding the tree rather than drawing it, hence I have not used it much.

I have also some python scripts that generates and compiles the tree.

MC

**Comment by facontidavide** [comment]
Cool... unfortunately I don't know Javascript and I can't help much on that side ;)

My idea was to avoid code generation, mainly because it is complicated to do 2 way transformations.
IMHO the factory approach is more flexible.
That would require to keep the key/value parameters defined by the original project, because they might be required to pass custom arguments to the constructors.

I will prepare a simple demo to show you what I mean.
