### ISSUE TITLE
Improving Reactivity using Implicit Sequences is unclear

### ISSUE THREAD

**Issue by jasonbeach** [miccol/Behavior-Tree#17]
Hi Michele,
  I am new to BTs and AI in general so let me say your book as been extremely helpful.  I am trying to understand the design principle "Improving Reactivity using Implicit Sequences".  Figure 3.3:
![capture](https://user-images.githubusercontent.com/2664807/36033113-041bc834-0d7e-11e8-811b-3f71391fedf1.PNG)
This is Figure 3.2 rearranged so that if the agent has already passed through the door, it doesn't try to open or unlock the door.  What I don't understand in Figure 3.3 is that if the Open Door action returns success then the whole fallback node would return success and the agent never passes through the door.  Same with unlocking the door--the unlock action (if performed) would return success when complete causing the fallback node to return success even though the agent never opened the door or went though it.   It almost seems like it should be like this:
![reactivebt](https://user-images.githubusercontent.com/2664807/36036883-0fa4139a-0d89-11e8-9c69-a0cbf64b4d94.png)
which follows the PPA methodology nicely.  Am I missing something?  Thanks again--this is awesome!

Jason

**Comment by miccol** [comment]
Hi Jason,

First, thank you for reading our book.
I understand your doubt. The Implicit sequence is used to incrementally create a BT that brings the agent to a goal. Each increment adds a capability to the robot making it more "robust" (i.e. it can handle more situations). It is true that once an Action returns Success the whole Fallback returns Success. However, keep in mind that you are constantly ticking the tree, hence if you need to, for example, _pass through door_ you will re-tick the BT of Figure 3.3. 

I understand that we always tend to see a BT as something that returns Success when it is done and returns Failure if it cannot do it. But, in the case of the Fallback (hence in the implicit sequence), you may see the BT as "deal with your current situation" so the return status Success makes sense. 

If in your implementation this causes problems, remember that you can have durative actions in the BT, (i.e., actions that are executed as long as they receive ticks, similarly to actions in a Teleo-reactive program and Subsumption architecture) and you define in the Condition when to tick the actions. The BT in Figure 3.3 would work also in case of durative actions.

Let me know if you have further questions.

Regards
Michele
