### ISSUE TITLE
Work on a improved visualization of the tree.

### ISSUE THREAD

**Issue by ewerlopes** [miccol/Behavior-Tree#3]
I think we should look for a better visualization.

**Comment by miccol** [comment]
For a free, open source and OS-independent visualization, OpenGL is probably the only decent choice we have right now. Do you have any alternatives?

**Comment by ewerlopes** [comment]
Indeed! I think it is a good thing to stick with OpenGL. What I really think should be improved is the graphics! So, it is a bit primitive yet... I mean... it is the first version and demands improvements.  

Also, I think that the visualization implemented [here](https://github.com/ewerlopes/beetree) could be an alternative if there is any unnecessary resource demand by the use of OpenGL.

**Comment by miccol** [comment]
That is with graphviz, I have the same visualization on my python implementation of BTs (soon available).
That visualization does only outputs a png (or pdf) file. It is not an on screen visualization in which we can visualize which subtree is currently ticked (executed) as in OpenGL.

**Comment by ewerlopes** [comment]
Yes. That is right! The "static output" by graphviz is the major drawback. But, I must agree that it is simple and clean graph output. We should get a pretty OpenGL representation.

**Comment by int3ll3ct** [comment]
I hacked some slight changes to the visualization on my machine - nothing major, mostly optimizing the spacing of the nodes at each depth layer - which made the visualization more useful to me.  I'll post  a screenshot later today.

**Comment by miccol** [comment]
Awesome, keep us posted!

**Comment by ewerlopes** [comment]
Hey @int3ll3ct... That is awesome! Keep in touch.

**Comment by int3ll3ct** [comment]
Here's my current slightly modded BT viz, note that I'm using the ROS-Behavior-Tree code as a baseline.  My goal was to avoid nodes visually overlapping, which was a problem with my tree.

![image](https://cloud.githubusercontent.com/assets/7289659/13024415/81010eda-d1c2-11e5-99b9-00bf6d52dafb.png)

**Comment by miccol** [comment]
@int3ll3ct Have you tried to use the PgUp/PgDown key to increase/decrease the spacing between nodes?

**Comment by int3ll3ct** [comment]
Yes I did, but the existing viz algorithm overlaid my PanTiltServosOff and MemPriority nodes at any x spacing (the existing algorithm computed their centers to be dead-centered over each other).  What I have done is no prettier, but will always maximize the space between nodes at every depth level.  I also added a JSON parser for the BT visual editor at Behavior3.com, in order to create trees visually, and read in trees from JSON files, and I added more decorators and a couple of default actions.  Out of the 3 BT implementations I was considering using, I felt yours dealt with the node "halt" concept the best, so I switched over to your implementation (I first started first using the almc implementation, which seems to be an ancestor of your implementation.)

**Comment by miccol** [comment]
@int3ll3ct I agree, sometimes the overlapping can be tricky to solve wil PgUp/Pg Down. Fell free to upload the improvements.
I am in contact with the developer of Behavior3.com I also had in mind of doing a parsing from JSON files (I have also asked him to add the possibility to draw the BTs from top down). Unfortunately this is still in the TODO list.

Yes, I was working with almc, he is my colleague.  We now work on different topics, so I have decided to have my own library.  

I feel flattered in having people using BT++, I honestly did not expect to have many people using it. Fell free to comment or request improvements/additions.

**Comment by miccol** [comment]
The version 1.2 of the ROS library has an improved visualization.

**Comment by miccol** [comment]
done in version 1.3
