### ISSUE TITLE
Why is 'while' suggested to be used in the ActionNode?

### ISSUE THREAD

**Issue by tomchambers2** [miccol/Behavior-Tree#7]
In the [example](https://github.com/miccol/Behavior-Tree/blob/master/src/ActionNodeExample.cpp#L41-L53), it uses a while loop to continually execute whatever the action does while it's running. What's the reason this should be done rather than an if statement that is executed once for each tick?

**Comment by miccol** [comment]
That is to let the action run its loops with frequency different than the tick frequency. 
You can have "synchronized" loops using the if-statement you mentioned. But be careful with the synchronization (i.e. Semaphore.Wait() ).
