### ISSUE TITLE
coding style

### ISSUE THREAD

**Issue by facontidavide** [miccol/Behavior-Tree#8]
Hi,

first of all, thanks for making this code available.
If I can make a suggestions, there are few coding styles that can help improving the maintenability and readability of the code.

1) Don't expose constants such has the node name and type as public member.
You don't want the user to be able to change them. Make the private and provide public getters.

2) use naming conventions instead of CamelCase everywhere. I would recommend https://google.github.io/styleguide/cppguide.html

3) Remove the member [NodeType Type](https://github.com/miccol/Behavior-Tree/blob/master/lib/include/TreeNode.h#L67). You are just duplicating the information with no real benefit for maintainers and users.

I am working on these improvements here: https://github.com/facontidavide/Behavior-Tree

Regards

Davide

**Comment by miccol** [comment]
Hi, I totally agree with you about the coding style and I have already done that in the ROS version of the BT library a while ago (https://github.com/miccol/ROS-Behavior-Tree  , version 1.2).  I am planning to do the same in the "ROS free" version as well.

Thanks
